Revert "followed tutorial to this part, getting Error CS0579 Duplicate 'global::System.Runtime.Versioning.TargetFrameworkAttribute'"
This reverts commit 3ef59fb0a067fb9e7031f3681a450f668e16ba09.

Not sure what got messed up following the tutorial, so backtracking